// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file message.proto (package serial, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message as Message$1 } from "@bufbuild/protobuf";

/**
 * Describes the file message.proto.
 */
export const file_message: GenFile = /*@__PURE__*/
  fileDesc("Cg1tZXNzYWdlLnByb3RvEgZzZXJpYWwibQoHTWVzc2FnZRImCgloYW5kc2hha2UYCiABKAsyES5zZXJpYWwuSGFuZHNoYWtlSAASLwoOY29udHJvbF9wYWNrZXQYFCABKAsyFS5zZXJpYWwuQ29udHJvbFBhY2tldEgAQgkKB2NvbnRlbnQiMAoJSGFuZHNoYWtlEiMKBHR5cGUYCiABKA4yFS5zZXJpYWwuSGFuZHNoYWtlVHlwZSL7AgoNQ29udHJvbFBhY2tldBIPCgdhZGRyZXNzGAogASgNEjMKBWRyaXZlGBQgASgLMiIuc2VyaWFsLkNvbnRyb2xQYWNrZXQuRHJpdmVDb21tYW5kSAASMQoEaGFsdBgoIAEoCzIhLnNlcmlhbC5Db250cm9sUGFja2V0LkhhbHRDb21tYW5kSAASRAoOZW1lcmdlbmN5X3N0b3AYMiABKAsyKi5zZXJpYWwuQ29udHJvbFBhY2tldC5FbWVyZ2VuY3lTdG9wQ29tbWFuZEgAGlEKDERyaXZlQ29tbWFuZBIyCglkaXJlY3Rpb24YCiABKA4yHy5zZXJpYWwuQ29udHJvbFBhY2tldC5EaXJlY3Rpb24SDQoFc3BlZWQYFCABKA0aDQoLSGFsdENvbW1hbmQaFgoURW1lcmdlbmN5U3RvcENvbW1hbmQiJgoJRGlyZWN0aW9uEgsKB0ZPUldBUkQQABIMCghCQUNLV0FSRBABQgkKB2NvbW1hbmQqKgoNSGFuZHNoYWtlVHlwZRILCgdSRVFVRVNUEAASDAoIUkVTUE9OU0UQAWIGcHJvdG8z");

/**
 * @generated from message serial.Message
 */
export type Message = Message$1<"serial.Message"> & {
  /**
   * @generated from oneof serial.Message.content
   */
  content: {
    /**
     * @generated from field: serial.Handshake handshake = 10;
     */
    value: Handshake;
    case: "handshake";
  } | {
    /**
     * @generated from field: serial.ControlPacket control_packet = 20;
     */
    value: ControlPacket;
    case: "controlPacket";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message serial.Message.
 * Use `create(MessageSchema)` to create a new message.
 */
export const MessageSchema: GenMessage<Message> = /*@__PURE__*/
  messageDesc(file_message, 0);

/**
 * @generated from message serial.Handshake
 */
export type Handshake = Message$1<"serial.Handshake"> & {
  /**
   * @generated from field: serial.HandshakeType type = 10;
   */
  type: HandshakeType;
};

/**
 * Describes the message serial.Handshake.
 * Use `create(HandshakeSchema)` to create a new message.
 */
export const HandshakeSchema: GenMessage<Handshake> = /*@__PURE__*/
  messageDesc(file_message, 1);

/**
 * @generated from message serial.ControlPacket
 */
export type ControlPacket = Message$1<"serial.ControlPacket"> & {
  /**
   * @generated from field: uint32 address = 10;
   */
  address: number;

  /**
   * @generated from oneof serial.ControlPacket.command
   */
  command: {
    /**
     * @generated from field: serial.ControlPacket.DriveCommand drive = 20;
     */
    value: ControlPacket_DriveCommand;
    case: "drive";
  } | {
    /**
     * @generated from field: serial.ControlPacket.HaltCommand halt = 40;
     */
    value: ControlPacket_HaltCommand;
    case: "halt";
  } | {
    /**
     * @generated from field: serial.ControlPacket.EmergencyStopCommand emergency_stop = 50;
     */
    value: ControlPacket_EmergencyStopCommand;
    case: "emergencyStop";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message serial.ControlPacket.
 * Use `create(ControlPacketSchema)` to create a new message.
 */
export const ControlPacketSchema: GenMessage<ControlPacket> = /*@__PURE__*/
  messageDesc(file_message, 2);

/**
 * @generated from message serial.ControlPacket.DriveCommand
 */
export type ControlPacket_DriveCommand = Message$1<"serial.ControlPacket.DriveCommand"> & {
  /**
   * @generated from field: serial.ControlPacket.Direction direction = 10;
   */
  direction: ControlPacket_Direction;

  /**
   * @generated from field: uint32 speed = 20;
   */
  speed: number;
};

/**
 * Describes the message serial.ControlPacket.DriveCommand.
 * Use `create(ControlPacket_DriveCommandSchema)` to create a new message.
 */
export const ControlPacket_DriveCommandSchema: GenMessage<ControlPacket_DriveCommand> = /*@__PURE__*/
  messageDesc(file_message, 2, 0);

/**
 * @generated from message serial.ControlPacket.HaltCommand
 */
export type ControlPacket_HaltCommand = Message$1<"serial.ControlPacket.HaltCommand"> & {
};

/**
 * Describes the message serial.ControlPacket.HaltCommand.
 * Use `create(ControlPacket_HaltCommandSchema)` to create a new message.
 */
export const ControlPacket_HaltCommandSchema: GenMessage<ControlPacket_HaltCommand> = /*@__PURE__*/
  messageDesc(file_message, 2, 1);

/**
 * @generated from message serial.ControlPacket.EmergencyStopCommand
 */
export type ControlPacket_EmergencyStopCommand = Message$1<"serial.ControlPacket.EmergencyStopCommand"> & {
};

/**
 * Describes the message serial.ControlPacket.EmergencyStopCommand.
 * Use `create(ControlPacket_EmergencyStopCommandSchema)` to create a new message.
 */
export const ControlPacket_EmergencyStopCommandSchema: GenMessage<ControlPacket_EmergencyStopCommand> = /*@__PURE__*/
  messageDesc(file_message, 2, 2);

/**
 * @generated from enum serial.ControlPacket.Direction
 */
export enum ControlPacket_Direction {
  /**
   * @generated from enum value: FORWARD = 0;
   */
  FORWARD = 0,

  /**
   * @generated from enum value: BACKWARD = 1;
   */
  BACKWARD = 1,
}

/**
 * Describes the enum serial.ControlPacket.Direction.
 */
export const ControlPacket_DirectionSchema: GenEnum<ControlPacket_Direction> = /*@__PURE__*/
  enumDesc(file_message, 2, 0);

/**
 * @generated from enum serial.HandshakeType
 */
export enum HandshakeType {
  /**
   * @generated from enum value: REQUEST = 0;
   */
  REQUEST = 0,

  /**
   * @generated from enum value: RESPONSE = 1;
   */
  RESPONSE = 1,
}

/**
 * Describes the enum serial.HandshakeType.
 */
export const HandshakeTypeSchema: GenEnum<HandshakeType> = /*@__PURE__*/
  enumDesc(file_message, 0);

